---
title: Compilation pipeline of Zom v0.4.0
---
flowchart TB
    classDef Rust fill:#dea584;
    classDef Zom fill:#E7DB3C;
    classDef Other fill:lightblue;
    lexer("Lexer"):::Zom
    parser("Parser"):::Zom
    typecheck("Type Checker"):::Zom
    scheme_exp("Scheme expanssion"):::Zom
    codegen("LLVM-IR gen"):::Rust
    compile("Compilation to obj"):::Rust
    link("Link .obj"):::Rust
    bin("Binary / Library Result"):::Other
    metadata("Metadata"):::Other


    subgraph fe ["Front end (Zom)"]
        direction TB
        lexer --> parser ;
        parser --> typecheck;
    end

    subgraph se ["Scheme Expanssion (Zom)"]
        direction TB
        typecheck --> scheme_exp;
        scheme_exp --"As many time needed"--> scheme_exp
    end
    
    subgraph be ["Back End (Rust)"]
        direction TB
        scheme_exp --"Serializer / Deserializer"--> codegen;
        codegen --> compile
    end

    fe -..-> metadata
    se -..-> metadata
    be -..-> metadata

    metadata --> lnk

    subgraph lnk ["Link (Rust)"]
        direction TB
        compile --"LLD"--> link;
        link --> bin
    end
