
name: Rust tests for

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests-zom_fe:
    name: "${{ github.job }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.3.0

    - name: Build
      working-directory: ./zom_fe
      run: cargo build --release --verbose

    - name: Run tests
      working-directory: ./zom_fe
      run: cargo test --release --verbose

  tests-zom_common:
    name: "${{ github.job }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.3.0

    - name: Build
      working-directory: ./zom_fe
      run: cargo build --release --verbose

    - name: Run tests
      working-directory: ./zom_fe
      run: cargo test --release --verbose
